### ISSUE TITLE
[PE-D][Tester B] Unsynchronised emails

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-3/tp#140]
![image.png](https://raw.githubusercontent.com/Polygonalr/ped/master/files/79535708-f119-4a8b-ac83-cedccdf42c49.png)

Actual person entry has email, but the socials panel at the right side shows null? Not sure why they are considered as separate entities.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Polygonalr/ped#5

**Comment by turretDive** [comment]
This has an intended purpose which we will address in the UG
