### ISSUE TITLE
[PE-D][Tester C] PreferCommand reset the person list

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-3/tp#147]
Before running:

![image.png](https://raw.githubusercontent.com/Tex-Tang/ped/main/files/2f47d3a0-bab4-4517-897b-cd36cfaed76c.png)

After running `prefer 1 s/instagram`

![image.png](https://raw.githubusercontent.com/Tex-Tang/ped/main/files/8eb6fb6c-7785-41c9-bad3-9662c9b752bf.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Tex-Tang/ped#7

**Comment by turretDive** [comment]
Unable to replicate bug
