### ISSUE TITLE
[PE-D][Tester E] prefer Command does not Update the Social Pane

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-3/tp#174]
Executing the `prefer` command with the following input:

`prefer 1 s/Whatsapp`

does not edit the `preference` pane on the right hand side to `Whatsapp`, and instead is still displaying `NO_PREFERENCE`.
Perhaps the data might not be automatically updated upon command execution, which might lead the user to think that the data has not been saved.

![image.png](https://raw.githubusercontent.com/jasonchristopher21/ped/main/files/a3d7a8e2-b9d5-4dce-b76d-a236db24e589.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jasonchristopher21/ped#13

**Comment by turretDive** [comment]
Fixed
